services:
  personal-site:
    build: .
    ports:
      - "8080:80"
    container_name: personal-website

  todo-app:
    image: prologic/todo
    ports:
      - "8081:8000"
    container_name: todo-application